"""Add Asset model

Revision ID: 5e08ddd8afe1
Revises: c64c134c36e5
Create Date: 2025-05-01 23:47:25.480343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e08ddd8afe1'
down_revision = 'c64c134c36e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'animation', name='assettype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    # ### end Alembic commands ###
